apiVersion: v1
kind: Service
metadata:
  name: verademo-java-web
spec:
  type: NodePort
  selector:
    app: verademo-java-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000