apiVersion: v1
kind: Service
metadata:
  name: verademo-dotnet
spec:
  type: NodePort
  selector:
    app: verademo-dotnet
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001